### ISSUE TITLE
Hardcoded paths in library due to missing environment variable

### ISSUE THREAD

**Issue by Thomas0c** [du5rte/react-skroll#1]
It seems that a missing `NODE_ENV=production` in front of the `build:lib` command is causing the resulting library to included hardcoded paths for dev dependencies, e.g. `
var _index = require('/Users/<username>/Sites/react-skroll/node_modules/redbox-react/lib/index.js');`.

I discovered this when I pulled and tried to use `react-skroll` from `npm` and wasn't able to use the library b/c of this. Adding `NODE_ENV=production` to `build:lib` seems to fix that issue, so the command becomes: `NODE_ENV=production babel src --out-dir lib`.

**Comment by du5rte** [comment]
Oh wow I had no idea, thanks for spotting Thomas 👍 do you want to submit a merge?
