### ISSUE TITLE
Would you be open to speed based scroll snapping?

### ISSUE THREAD

**Issue by younanjo** [du5rte/react-skroll#6]
Hi,

I've been looking at your lib and whilst i can fork and do my own thing, i was wondering if you think scroll speed based snapping would be useful for this module.

right now, the snapping only occurs where user has stopped scrolling, i was thinking to introduce another option, where snapping (autoFrame) can occur when scroll speed < x.

**Comment by du5rte** [comment]
@younanjo Might be a good new feature :) I'm open to ideas!
