### ISSUE TITLE
Can't resolve 'react-native-web/dist/exports/Animated' 

### ISSUE THREAD

**Issue by dz3264** [du5rte/react-skroll#8]
use  ScrollProvider, Scroller,  only and get error as following:

./node_modules/react-skroll/lib/Scroller.js
Module not found: Can't resolve 'react-native-web/dist/exports/Animated' in '/Users/diana/DREP/official-website/node_modules/react-skroll/lib'

**Comment by du5rte** [comment]
Should be fixed in @0.7.2
